version: '3'
services:
  outfit-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn outfitRecommendationAppBackend.wsgi:application --bind 0.0.0.0:8000
    network_mode: "host"
    restart: "unless-stopped"



