# Generated by Django 5.0.3 on 2024-06-15 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
                ('subCategory', models.CharField(max_length=30)),
                ('pattern', models.CharField(blank=True, max_length=30, null=True)),
                ('material', models.CharField(blank=True, max_length=30, null=True)),
                ('seasons', models.CharField(blank=True, max_length=60, null=True)),
                ('occasions', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wardrobe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemProbability',
            fields=[
                ('outfitItem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='itemprobability', serialize=False, to='app.outfititem')),
                ('sunnyHot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sunnyMild', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sunnyCold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rainyHot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rainyMild', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rainyCold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overcastHot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overcastMild', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overcastCold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('snowyHot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('snowyMild', models.DecimalField(decimal_places=2, max_digits=5)),
                ('snowyCold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preference', models.DecimalField(decimal_places=6, max_digits=10)),
                ('weatherSliderValue', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatureSliderValue', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=30)),
                ('images', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('posted_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=14)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.outfititem')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=30)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('worn_clothes_percentage', models.FloatField()),
                ('worn_outfits_percentage', models.FloatField()),
                ('worn_outfits', models.IntegerField()),
                ('total_outfits', models.IntegerField()),
                ('is_latest', models.BooleanField(default=False)),
                ('wardrobe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.wardrobe')),
            ],
        ),
        migrations.AddField(
            model_name='outfititem',
            name='wardrobe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wardrobe'),
        ),
        migrations.CreateModel(
            name='WornOutfits',
            fields=[
                ('date', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('was_recommended', models.BooleanField(default=False)),
                ('body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body', to='app.outfititem')),
                ('bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottom', to='app.outfititem')),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='app.outfititem')),
                ('top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top', to='app.outfititem')),
            ],
        ),
    ]
