# Generated by Django 4.2.9 on 2024-03-19 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wardrobe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('pattern', models.CharField(blank=True, max_length=30, null=True)),
                ('material', models.CharField(blank=True, max_length=30, null=True)),
                ('season', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('wardrobe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wardrobe')),
            ],
        ),
    ]
