# Generated by Django 5.0.3 on 2024-04-06 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_outfititem_name_remove_outfititem_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProbability',
            fields=[
                ('outfitItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.outfititem')),
                ('sunnyHot', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sunnyMild', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sunnyCold', models.DecimalField(decimal_places=2, max_digits=3)),
                ('rainyHot', models.DecimalField(decimal_places=2, max_digits=3)),
                ('rainyMild', models.DecimalField(decimal_places=2, max_digits=3)),
                ('rainyCold', models.DecimalField(decimal_places=2, max_digits=3)),
                ('overcastHot', models.DecimalField(decimal_places=2, max_digits=3)),
                ('overcastMild', models.DecimalField(decimal_places=2, max_digits=3)),
                ('overcastCold', models.DecimalField(decimal_places=2, max_digits=3)),
                ('snowyHot', models.DecimalField(decimal_places=2, max_digits=3)),
                ('snowyMild', models.DecimalField(decimal_places=2, max_digits=3)),
                ('snowyCold', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
