# Generated by Django 5.0.3 on 2024-04-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_itemprobability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprobability',
            name='overcastCold',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemprobability',
            name='overcastHot',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemprobability',
            name='overcastMild',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemprobability',
            name='rainyCold',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemprobability',
            name='rainyHot',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemprobability',
            name='rainyMild',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemprobability',
            name='snowyCold',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemprobability',
            name='snowyHot',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemprobability',
            name='snowyMild',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemprobability',
            name='sunnyCold',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemprobability',
            name='sunnyHot',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemprobability',
            name='sunnyMild',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
