# Generated by Django 5.0.3 on 2024-04-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_itemprobability_overcastcold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WornOutfits',
            fields=[
                ('date', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('bottom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_bottom', to='app.outfititem')),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_shoes', to='app.outfititem')),
                ('top', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_top', to='app.outfititem')),
            ],
        ),
    ]
