# Generated by Django 5.0.3 on 2024-04-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_wornoutfits'),
    ]

    operations = [
        migrations.AddField(
            model_name='wornoutfits',
            name='user_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
