# Generated by Django 5.0.3 on 2024-04-16 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_wornoutfits_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wornoutfits',
            name='bottom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom', to='app.outfititem'),
        ),
        migrations.AlterField(
            model_name='wornoutfits',
            name='shoes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='app.outfititem'),
        ),
        migrations.AlterField(
            model_name='wornoutfits',
            name='top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top', to='app.outfititem'),
        ),
    ]
