# Generated by Django 4.2.9 on 2024-04-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_marketplaceitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceitems',
            name='posted_date',
            field=models.DateTimeField(),
        ),
    ]
