# Generated by Django 4.2.9 on 2024-04-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_marketplaceitems_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitems',
            name='location',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
