# Generated by Django 4.2.9 on 2024-04-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_marketplaceitems_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplaceitems',
            old_name='outfit_id',
            new_name='outfit',
        ),
    ]
