# Generated by Django 4.2.9 on 2024-04-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_marketplaceitems_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceitems',
            name='brand',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='marketplaceitems',
            name='condition',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='marketplaceitems',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='marketplaceitems',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='marketplaceitems',
            name='size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='marketplaceitems',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
