# Generated by Django 4.2.9 on 2024-05-02 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_marketplaceitems_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('worn_clothes_percentage', models.FloatField()),
                ('worn_outfits_percentage', models.FloatField(blank=True, null=True)),
                ('is_latest', models.BooleanField(default=False)),
                ('wardrobe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.wardrobe')),
            ],
        ),
    ]
