# Generated by Django 4.2.9 on 2024-05-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_user_id_wornoutfits_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='season',
            field=models.CharField(default='Spring', max_length=30),
            preserve_default=False,
        ),
    ]
