# Generated by Django 4.2.9 on 2024-05-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_stats_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='worn_outfits_percentage',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
