# Generated by Django 4.2.9 on 2024-05-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_stats_worn_outfits_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='total_outfits',
            field=models.IntegerField(default=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='worn_outfits',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
    ]
