# Generated by Django 4.2.9 on 2024-05-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_stats_total_outfits_stats_worn_outfits'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprobability',
            name='preference',
            field=models.DecimalField(decimal_places=6, default=0.5, max_digits=10),
            preserve_default=False,
        ),
    ]
