# Generated by Django 4.2.9 on 2024-05-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_itemprobability_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitems',
            name='phone_number',
            field=models.CharField(default='0721213037', max_length=14),
            preserve_default=False,
        ),
    ]
