# Generated by Django 4.2.9 on 2024-05-23 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_itemprobability_outfititem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprobability',
            name='outfitItem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='itemprobability', serialize=False, to='app.outfititem'),
        ),
    ]
