# Generated by Django 4.2.9 on 2024-05-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_itemprobability_outfititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprobability',
            name='temperatureSliderValue',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemprobability',
            name='weatherSliderValue',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
            preserve_default=False,
        ),
    ]
