# Generated by Django 4.2.9 on 2024-05-25 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_itemprobability_temperatureslidervalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wornoutfits',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body', to='app.outfititem'),
        ),
        migrations.AlterField(
            model_name='wornoutfits',
            name='bottom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottom', to='app.outfititem'),
        ),
        migrations.AlterField(
            model_name='wornoutfits',
            name='top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top', to='app.outfititem'),
        ),
    ]
