# Generated by Django 4.2.9 on 2024-05-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_wornoutfits_body_alter_wornoutfits_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wornoutfits',
            name='was_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outfititem',
            name='color',
            field=models.CharField(max_length=100),
        ),
    ]
