# Generated by Django 4.2.9 on 2024-02-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfitRecommendationAppBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfititem',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
