# Generated by Django 4.2.9 on 2024-02-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfitRecommendationAppBackend', '0002_alter_outfititem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfititem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
